### ISSUE TITLE
Support denying a MIME type for SFTP uploads

### ISSUE THREAD

**Issue by sburkett** [Castaglia/proftpd-mod_mime#9]
Hi there. Just trying out the module and ran into this issue. I've denied "image/png" files, as a simple test. When I upload a png file, it initially denies it (I guess), then reconnects immediately and sends it successfully. As a side note, I am using a virtual user configuration inside of proftpd.

```
Status:	Starting upload of c:\temp\test.png
Command:	put "c:\temp\test.png" "test.png"
Command:	local:c:\temp\test.png => remote:/test.png
Error:	Server unexpectedly closed network connection
Error:	File transfer failed
Status:	Disconnected from server
Status:	Connecting to MY_IP:2222...
Status:	Connected to MY_IP
Status:	Starting upload of c:\temp\test.png
Status:	Retrieving directory listing of "/"...
Status:	Listing directory /
Status:	File transfer successful, transferred 107,027 bytes in 1 second
```

Here is the config inside of my virtual host in proftpd:

```
LoadModule mod_mime.c

<VirtualHost MY_IP>

   ...

    # MIME filtering
    MIMEEngine on

    <Directory /some/dir>
      # Deny png files as a simple test
      MIMEDenyType image/png
    </Directory>

</VirtualHost>
```

### UPDATE

I realized that I needed to add the `MIMETable` directive. Per the docs, I tried to include the `MIMEEngine on` block inside of `<Global>` but it threw an error when I did that ... so I just added it outside of that. But now, instead of denying it, then reconnecting and sending it anyway, it just sends it right away with no denying at all.

```
LoadModule mod_mime.c

<IfModule mod_mime.c>
  MIMEEngine on
  MIMETable /usr/share/misc/misc
</IfModule>

  ...

<VirtualHost MY_IP>

   ...
    <Directory /some/dir>
      # Deny png files as a simple test
      MIMEDenyType image/png
    </Directory>

</VirtualHost>

```

Thanks in advance for any guidance!

**Comment by sburkett** [comment]
Here is the error I mentioned above:

```
fatal: MIMETable: directive not allowed in <VirtualHost> context on line 500 of '/etc/proftpd.conf'
```

After looking at the code, it would appear the documentation is incorrect, as the `MIMETable` directive can only be placed in the root of the conf file.

```
MODRET set_mimetable(cmd_rec *cmd) {
  ...
  CHECK_CONF(cmd, CONF_ROOT);

  if (cmd->argc == 1) {
    CONF_ERROR(cmd, "wrong number of parameters");
  }
  ...
```

**Comment by sburkett** [comment]
I'm wondering if it is because I am doing this over `mod_sftp` rather than standard `ftp`?

**Comment by Castaglia** [comment]
That is certainly possible; I'm not sure I've done much testing of `mod_mime` when using with `mod_sftp`.  Will try to find some time to do so soon.

**Comment by Castaglia** [comment]
This should now be fixed in master.  Cheers!
